name: Release zip

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: zip files
      run: |
        bash ./build.sh ${{ github.ref_name }}
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Release ${{ github.ref_name }}"
        tag_name: "${{ github.ref_name }}"
        draft: true
        files: |
          ./dist/blender-exporter-colmap_${{ github.ref_name }}.zip
        prerelease: false
        target_commitish: main
